spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/greenlight?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: grnmaster
    password: password
  flyway:
    enabled: false
    encoding: UTF-8
    url: jdbc:mysql://localhost:3307/greenlight
    user: grnmaster
    password: password
    baseline-on-migrate: true
    locations: classpath:db/migrations/local,db/migrations/seed
    baseline-version: 1.0.0
    ignore-migration-patterns: "*:pending"
    clean-on-validation-error: true
    clean-disabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
# HS512 ???? ?? 64byte ??? ??? ?????
jwt:
  authorization-header: Authorization
  access-header: access_token
  refresh-header: refresh_token
  token-header-prefix: Bearer
  secret-key: Zi1sYWItZ3JlZW5saWdodC1zcHJpbmctYm9vdC1qd3QtZi1sYWItZ3JlZW5saWdodC1zcHJpbmctYm9vdC1qd3QK
  access-token-validity-in-seconds: 1 # 30? 60? * 30?
  refresh-token-validity-in-seconds: 86400 # 1? 60? * 1440 (24??) * 1?

server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    org.springframework: DEBUG
